apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myproject.id
  namespace: myproject
spec:
  secretName: myproject.id-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "myproject.id"