memory_limit = -1
max_execution_time = 7200
max_input_time = 7200
post_max_size = 2000M
upload_max_filesize = 2000M
max_input_vars = 10000

error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
display_errors = on
log_errors = On
error_log = /var/log/php_errors.log

date.timezone = Asia/Jakarta
expose_php = Off